### ISSUE TITLE
Is there a way for payed suport

### ISSUE THREAD

**Issue by adopilot** [pszafer/SambaForFreeradiusPFSENSE#1]
Hello there, Thanks on great work.
I am wondering is there way to my company hire you to make this combination works on pfsense 2.1.5
verisono.
We have an idea to make freebsd routers act also as samba file shares and to these samba file shares be protected by LDAP cardinalse. 
Provided by Domain Contolorol

Thanx in advanced

**Comment by pszafer** [comment]
sure, we could try do that.

Questions:
- why pfSense 2.1?
  pfSense 2.2 has only 5 open issues (https://redmine.pfsense.org/projects/pfsense/roadmap), it is in RC stage so it could happen any time when they publish new version of pfSense.

And with FreeBSD 10, we have new package manager, newer samba - 4.1 minimum and it can act as ADC.

Of course if you want to stick with 2.1 I don't think there will be a problem

**Comment by adopilot** [comment]
Thanx on replay.
I am not sticked to verison 2.1.x
I am OK to move up to 2.2
I mentioned 2.1.5 version because you have tutorials for 2.1
Do you have some other media for communicating over viber or gtalk or fixed line
So I can send you more information what I am trying to accomplish.
My name is admre and at gtalk I am adopilot@gmail.com 
can you contact me please over that so we can discous more in detail, so you can 
make proforma for your suport
